### ISSUE TITLE
Multiple routing bugs

### ISSUE THREAD

**Issue by aTmb405** [aTmb405/breads-client#10]
- [x] When user switches from one user's readings list to another, it doesn't load
- [x] When user updates their info, it displays in readings, but not in user aside
- [x] User's notifications hit 0 only after refresh
- [x] User should see their new reading without being sent to global page

**Comment by farukrana** [comment]
> * [x]  When user switches from one user's readings list to another, it doesn't load
> * [x]  When user updates their info, it displays in readings, but not in user aside
> * [x]  User's notifications hit 0 only after refresh
> * [x]  User should see their new reading without being sent to global page

remove
[]()
