### ISSUE TITLE
Transition to react-router-dom@6 

### ISSUE THREAD

**Issue by takanome-dev** [aTmb405/breads-client#112]
I'd like to update react-router-dom to [react-router-dom@6](https://reactrouter.com/docs/en/v6/getting-started/installation). But I have this error : "import declaration conflicts with local declaration of 'Routes'".
So I don't know if I should change the Routes files or not??

**Comment by aubundy** [comment]
From react router's [docs](https://reactrouter.com/docs/en/v6/upgrading/v5#introduction), they suggest not upgrading from v5 yet unless there are just a few routes in the project. Let's hold off on doing this for now.
