### ISSUE TITLE
Begin implementing Redux style guide

### ISSUE THREAD

**Issue by aTmb405** [aTmb405/breads-client#23]
https://redux.js.org/style-guide/style-guide

- [x] structure files as feature folders or Ducks
- [x] normalize complex nested/relational state
- [ ] _use static typing_
- [X] Do not mutate state
- [X] Reducers must not have side effects
- [X] Do not put non-serializable values in state or actions
- [x] only one redux store per app
- [ ] _use Redux Toolkit for writing Redux Logic_
- [ ] _Use Immer for writing immutable updates_
- [X] put as much logic as possible in Reducers
- [x] reducers should own the state shape
- [x] name state slices based on the stored data
- [x] treat reducers as state machines
- [x] model actions as events, not setters
- [x] write meaningful action names
- [x] allow many reducers to respond to the same action
- [x] avoid dispatching many actions sequentially
- [x] evaluate where each piece of state should live
- [x] connect more components to read data from the store
- [X] use object shorthand form of mapDispatch with connect
- [ ] _call useSelector multiple times in function components_
- [X] use Redux DevTools extension for debugging
- [x] use plain JS objects/arrays for state

**Comment by farukrana** [comment]
errors

**Comment by farukrana** [comment]
remove
